# Generated by Django 4.0.2 on 2022-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=24),
        ),
    ]
