# Generated by Django 4.0.2 on 2022-04-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_alter_reviews_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='date_add',
        ),
    ]
