# Generated by Django 4.0.2 on 2022-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_remove_reviews_product_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
