# Generated by Django 4.0.2 on 2022-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_feedback_alter_reviews_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email_recipient',
            field=models.EmailField(default='marketstuffdjango@gmail.com', max_length=254),
        ),
    ]
