# Generated by Django 4.0.2 on 2022-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_alter_feedback_email_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
