# Generated by Django 4.0.4 on 2022-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0046_remove_product_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
