# Generated by Django 4.0.4 on 2022-05-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_alter_product_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
