# Generated by Django 4.0.4 on 2022-05-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0052_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
