# Generated by Django 4.0.2 on 2022-03-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
