# Generated by Django 4.0.2 on 2022-03-15 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_product_reviews_reviews_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
