# Generated by Django 4.0.2 on 2022-03-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_product_category_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='products',
        ),
    ]
