# Generated by Django 4.0.2 on 2022-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_product_time_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_add',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование'),
        ),
    ]
