# Generated by Django 4.0.2 on 2022-04-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
