# Generated by Django 4.0.2 on 2022-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_alter_reviews_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
