# Generated by Django 4.0.2 on 2022-04-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_feedback_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone_number',
        ),
    ]
