# Generated by Django 4.0.4 on 2022-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_alter_basket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
